# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('thumbnail', models.CharField(max_length=1000)),
                ('video_path', models.CharField(max_length=1000)),
            ],
        ),
    ]
