# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20170726_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(max_length=1000, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_path',
            field=models.FileField(max_length=1000, upload_to=b''),
        ),
    ]
